### ISSUE TITLE
[newbie - question] video does not fit in "preview"

### ISSUE THREAD

**Issue by lblabr** [prasathmani/tinyfilemanager#980]
i'm looking for an universial tool for my raspi. i do same records with obs and store them locally, i would like to browse by directory and files.

i found your software looks great on the demo! if click on the left icon/filename the video opens, but does not really fit to the page, can this be configured somewhere, header is great, but video size needs to be adjusted. is that possible?

Thanks a lot!

Lars

**Comment by prasathmani** [comment]
replace
```css
.preview-video { position:relative;max-width:100%;height:0;padding-bottom:62.5%;margin-bottom:10px  }
```
to 

```css
.preview-video { position:relative;max-width:100%;height:75vh;margin-bottom:10px  }
```
